### ISSUE TITLE
Templates in edit summaries get expanded to HTML

### ISSUE THREAD

**Issue by Ostrzyciel** [femiwiki/DiscordRCFeed#66]
MediaWiki: 1.36.3
PHP: 7.4.27 (fpm-fcgi)
DiscordRCFeed: 1.0.2 (e87b8cc)

---

Consider a log entry like this ([link](https://nonsa.pl/index.php?title=Specjalna:Rejestr&logid=392812&uselang=en)): 
![image](https://user-images.githubusercontent.com/56843159/153363794-0f07e21b-418b-4db4-8d7f-56fd220b26a3.png)

Notice the `{{euro mecze}}` template mention in the edit summary. It shows up in the Discord feed as:

![image](https://user-images.githubusercontent.com/56843159/153363648-e5f1c316-2579-4875-bf94-e654bd05684a.png)

Which is the expanded content of this template after being parsed to HTML. In the case of larger templates (e.g., navboxes), this makes the RC message so big that it doesn't show up on the Discord feed at all.

This is contrary to the default MW RecentChanges behavior, where template mentions like this are simply left as-is.

**Comment by lens0021** [comment]
This is completely the same as https://github.com/kulttuuri/DiscordNotifications/issues/73, even the writer who made it is the same, it's me. I will upload a patch. Thank you for reporting this.

**Comment by lens0021** [comment]
As I don't know how Nonsensopedia deploys extensions, could I ask you a new release will be helpful to you? If not, I don't want to release a new version because it seems to be a minor fix to me. Thank you. @Ostrzyciel

**Comment by Ostrzyciel** [comment]
> As I don't know how Nonsensopedia deploys extensions, could I ask you a new release will be helpful to you? If not, I wouldn't release a new version immediately because it seems to be a minor fix to me. Thank you. @Ostrzyciel

We can manage without a release :)
Thanks for the fix. I can verify that it's working.
