### ISSUE TITLE
Links don't work when $wgServer is set for protocol relative

### ISSUE THREAD

**Issue by prodigion** [femiwiki/DiscordRCFeed#94]
```
$wgServer = "//site.org";
$wgCanonicalServer = "https://site.org";

```
Links don't get sent properly. On desktop it just appears as plaintext, but on mobile it shows as text links without the `http(s);`.

**Comment by lens0021** [comment]
Thank you for reporting this! I will merge the above patch which hopefully fix the issue.

**Comment by prodigion** [comment]
This appears to have fixed it, thanks!
